title: "phina.js ゲーム作成解説 15パズル"
summary: "javascriptのゲーム作成用ライブラリphina.jsを使ったゲーム作成の解説です。テーマは、15パズルです。phina.js Tips集を先に見て頂くと理解が早いかと思います。"
topics: ["phina","javascript","html5","ゲーム開発"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
#chapters:
