title: "phina.js ゲーム作成チュートリアル 15パズル"
summary: "javascriptのゲーム作成用ライブラリphina.jsのチュートリアルです。簡単な15パズルの作成を通してphina.jsの使い方を解説します。"
topics: ["phina","javascript","html5","ゲーム開発"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
#chapters:
