title: "phina.jsで作るブロック崩しゲーム"
summary: "定番のブロック崩しゲームの作成を通して、javascriptのゲームライブラリphina.jsを使ったゲームプログラミングの方法を紹介します。"
topics: ["javascript","html5","phina","ゲーム開発"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 01prepare
  - 02showpaddle
