title: "phina.js Tips集 【改】"
summary: "javascriptのゲームライブラリphina.jsの非公式Tips集です。Qiitaに掲載していたものを改訂しています。順次内容更新中。
"
topics: ["javascript","html5","phina","ゲーム開発"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - prologue
  - templete
  - shape001
  - shape002
  - shape003
  - shape004
  - shape005
  - shape006
  - shape007
  - shape008  
  - shape009
  - shape010
  - sprite001
  - sprite002
  - sprite003
  - sprite004
  - sprite05
  - sprite06
  - sprite07
  - sprite08
  - sprite09
  - asset01