title: "phina.js Tips集 下巻"
summary: "javascriptのゲーム作成用ライブラリphina.jsに関するTipsについて書いています。この本は下巻です。非公式ですが、少しでも参考になれば幸いです。順次更新していきますので、よろしければチェックをよろしくお願いします。"
topics: ["phina","javascript","html5","ゲーム開発"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
#chapters: